# Generated by Django 5.0.6 on 2024-05-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disc_Questions_Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DISC_PROFILE_ID', models.CharField(max_length=10, unique=True)),
                ('QUESTION', models.TextField()),
                ('A', models.CharField(max_length=100)),
                ('B', models.CharField(max_length=100)),
                ('C', models.CharField(max_length=100)),
                ('D', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disc_Score_Calculation_Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DISC_PROFILE_ID', models.CharField(max_length=10, unique=True)),
                ('D', models.CharField(max_length=3)),
                ('I', models.CharField(max_length=3)),
                ('S', models.CharField(max_length=3)),
                ('C', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='NVI_Questions_Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE_ID', models.CharField(max_length=10, unique=True)),
                ('IMAGE', models.ImageField(upload_to='hirexcel_webapp/images/NVI_Questions_Dataset')),
                ('OPTION1', models.CharField(max_length=3)),
                ('OPTION2', models.CharField(max_length=3)),
                ('OPTION3', models.CharField(max_length=3)),
                ('OPTION4', models.CharField(max_length=3)),
                ('OPTION5', models.CharField(max_length=3)),
                ('OPTION6', models.CharField(max_length=3)),
                ('OPTION7', models.CharField(max_length=3)),
                ('OPTION8', models.CharField(max_length=3)),
                ('ANSWERS', models.CharField(max_length=3)),
            ],
        ),
    ]
