# Generated by Django 5.0.6 on 2024-06-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirexcel_webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Position_Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JPC_ID', models.CharField(max_length=10, unique=True)),
                ('CATEGORY', models.CharField(max_length=100)),
                ('JOB_POSITION', models.CharField(max_length=100)),
                ('PERSONALITY_TRAITS', models.CharField(max_length=100)),
                ('COGNITIVE_SKILLS', models.CharField(max_length=100)),
                ('EMOTIONAL_INTELLIGENCE', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='disc_score_calculation_dataset',
            name='C',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='disc_score_calculation_dataset',
            name='D',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='disc_score_calculation_dataset',
            name='I',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='disc_score_calculation_dataset',
            name='S',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='nvi_questions_dataset',
            name='OPTION1',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='nvi_questions_dataset',
            name='OPTION2',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='nvi_questions_dataset',
            name='OPTION3',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='nvi_questions_dataset',
            name='OPTION4',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='nvi_questions_dataset',
            name='OPTION5',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='nvi_questions_dataset',
            name='OPTION6',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='nvi_questions_dataset',
            name='OPTION7',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='nvi_questions_dataset',
            name='OPTION8',
            field=models.CharField(max_length=4),
        ),
    ]
