# Generated by Django 5.0.6 on 2024-06-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirexcel_webapp', '0003_technical_questions_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Information',
            fields=[
                ('USER_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=100)),
                ('LAST_NAME', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PASSWORD', models.CharField(max_length=100)),
                ('CITY', models.CharField(blank=True, max_length=100, null=True)),
                ('COUNTRY', models.CharField(blank=True, max_length=100, null=True)),
                ('PHONE_NUMBER', models.CharField(max_length=15)),
            ],
        ),
    ]
