# Generated by Django 5.0.6 on 2024-06-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirexcel_webapp', '0004_assessment_bigfive_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_posting',
            name='JPC_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
