# Generated by Django 5.0.6 on 2024-06-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirexcel_webapp', '0004_user_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Seeker',
            fields=[
                ('JOB_SEEKER_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('LINKEDIN_PROFILE_URL', models.URLField(blank=True, null=True)),
                ('GITHUB_PROFILE_URL', models.URLField(blank=True, null=True)),
                ('RESUME_UPLOAD', models.FileField(blank=True, null=True, upload_to='hirexcel_webapp/JobSeekerResumes/')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.user_information')),
            ],
        ),
    ]
