# Generated by Django 5.0.6 on 2024-10-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirexcel_webapp', '0004_alter_cognitive_vi_question_dataset_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker_assessment',
            name='TOTAL_COMPLETION_TIME_REQUIRED',
            field=models.CharField(max_length=100),
        ),
    ]
