# Generated by Django 5.0.6 on 2024-06-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirexcel_webapp', '0005_job_seeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_position_criteria',
            name='id',
        ),
        migrations.AlterField(
            model_name='job_position_criteria',
            name='JPC_ID',
            field=models.CharField(editable=False, max_length=9, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Job_Seeker_Education',
            fields=[
                ('JOB_SEEKER_EDUCATION_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('INSTITUTION_NAME', models.CharField(max_length=100)),
                ('PROGRAM', models.CharField(blank=True, max_length=100, null=True)),
                ('START_DATE', models.DateField()),
                ('END_DATE', models.DateField(blank=True, null=True)),
                ('DEGREE', models.CharField(blank=True, max_length=100, null=True)),
                ('JOB_SEEKER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.job_seeker')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Seeker_Work_Experience',
            fields=[
                ('JOB_SEEKER_WE_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('COMPANY_NAME', models.CharField(max_length=100)),
                ('DESIGNATION', models.CharField(max_length=100)),
                ('START_DATE', models.DateField()),
                ('END_DATE', models.DateField()),
                ('JOB_SEEKER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.job_seeker')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('RECRUITER_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('COMPANY_NAME', models.CharField(max_length=100)),
                ('COMPANY_WEBSITE', models.URLField(blank=True, null=True)),
                ('INDUSTRY', models.CharField(blank=True, max_length=100, null=True)),
                ('COMPANY_SIZE', models.CharField(blank=True, max_length=100, null=True)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.user_information')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Posting',
            fields=[
                ('JOB_POST_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=100)),
                ('DESCRIPTION', models.TextField()),
                ('CITY', models.CharField(max_length=100)),
                ('COUNTRY', models.CharField(max_length=100)),
                ('JOB_TYPE', models.CharField(max_length=100)),
                ('JOB_POSITION', models.CharField(max_length=100)),
                ('PERSONALITY_TRAITS', models.TextField()),
                ('REQUIRED_SKILLS', models.TextField()),
                ('REQUIRED_QUALIFICATIONS', models.TextField()),
                ('EXPERIENCE_REQUIREMENTS', models.TextField()),
                ('REQUIRED_ASSESSMENTS', models.TextField()),
                ('TEST_CRITERIA', models.TextField(blank=True, null=True)),
                ('JPC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.job_position_criteria')),
                ('RECRUITER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.recruiter')),
            ],
        ),
    ]
