# Generated by Django 5.0.6 on 2024-06-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirexcel_webapp', '0006_remove_job_position_criteria_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('ASSESSMENT_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('ASSESSMENT_CATEGORY', models.CharField(max_length=200)),
                ('ASSESSMENT_SUB_TYPE', models.URLField(blank=True, null=True)),
                ('PASSING_SCORE', models.CharField(blank=True, max_length=100, null=True)),
                ('REQUIRED_COMPLETION_TIME', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BigFive_Assessment',
            fields=[
                ('BIG_FIVE_ASSESSMENT_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BigFive_Assessment_Answers',
            fields=[
                ('BIG_FIVE_ASSESSMENT_ANS_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('JOB_SEEKER_ANS', models.CharField(max_length=100)),
                ('BIG_FIVE_ASSESSMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.bigfive_assessment')),
            ],
        ),
        migrations.CreateModel(
            name='BigFive_Assessment_Result',
            fields=[
                ('BIG_FIVE_ASSESSMENT_RESULT_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('DIMENSIONS', models.CharField(max_length=100)),
                ('SCORE', models.IntegerField()),
                ('BIG_FIVE_ASSESSMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.bigfive_assessment')),
            ],
        ),
        migrations.CreateModel(
            name='BigFive_Characteristics_Dataset',
            fields=[
                ('BIG_FIVE_CHAR_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DIMENSIONS', models.CharField(max_length=100)),
                ('RANGES', models.CharField(max_length=100)),
                ('CATEGORIES', models.CharField(max_length=100)),
                ('PERSONALITY', models.CharField(max_length=100)),
                ('DESCRIPTION', models.TextField()),
                ('WORKPLACE_BEHAVIOR', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BigFive_Questions_Dataset',
            fields=[
                ('DIMENSION', models.CharField(max_length=100)),
                ('DIMENSION_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('QUESTION', models.TextField()),
                ('OPTION1', models.CharField(max_length=100)),
                ('OPTION2', models.CharField(max_length=100)),
                ('OPTION3', models.CharField(max_length=100)),
                ('OPTION4', models.CharField(max_length=100)),
                ('OPTION5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cognitive_Assessment',
            fields=[
                ('COGNITIVE_ASSESSMENT_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('COGNITIVE_ASSESSMENT_TYPE', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cognitive_Assessment_Results',
            fields=[
                ('COGNITIVE_ASSESSMENT_RESULT_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('COGNITIVE_VI_SCORE', models.IntegerField()),
                ('COGNITIVE_NVI_SCORE', models.IntegerField()),
                ('COGNITIVE_ASSESSMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.cognitive_assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Cognitive_NVI_Answers_Dataset',
            fields=[
                ('COGNITIVE_NVI_ANS_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('JOB_SEEKER_ANS', models.CharField(max_length=100)),
                ('IS_CORRECT', models.BooleanField()),
                ('COGNITIVE_ASSESSMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.cognitive_assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Cognitive_NVI_Questions_Dataset',
            fields=[
                ('NVI_IMAGE_QUESTION_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('IMAGE', models.ImageField(upload_to='hirexcel_webapp/images/NVI_Questions_Dataset')),
                ('OPTION1', models.CharField(max_length=4)),
                ('OPTION2', models.CharField(max_length=4)),
                ('OPTION3', models.CharField(max_length=4)),
                ('OPTION4', models.CharField(max_length=4)),
                ('OPTION5', models.CharField(max_length=4)),
                ('OPTION6', models.CharField(max_length=4)),
                ('OPTION7', models.CharField(max_length=4)),
                ('OPTION8', models.CharField(max_length=4)),
                ('ANSWERS', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cognitive_VI_Answers_Dataset',
            fields=[
                ('COGNITIVE_VI_ANS_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('JOB_SEEKER_ANS', models.CharField(max_length=100)),
                ('IS_CORRECT', models.BooleanField()),
                ('COGNITIVE_ASSESSMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.cognitive_assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Cognitive_VI_Question_Dataset',
            fields=[
                ('VI_QUESTION_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('QUESTION', models.TextField()),
                ('OPTION1', models.CharField(max_length=100)),
                ('OPTION2', models.CharField(max_length=100)),
                ('OPTION3', models.CharField(max_length=100)),
                ('OPTION4', models.CharField(max_length=100)),
                ('OPTION5', models.CharField(max_length=100)),
                ('OPTION6', models.CharField(max_length=100)),
                ('OPTION7', models.CharField(max_length=100)),
                ('OPTION8', models.CharField(max_length=100)),
                ('ANSWER', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DISC_Assessment',
            fields=[
                ('DISC_ASSESSMENT_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DISC_Assessment_Answer',
            fields=[
                ('DISC_ASSESSMENT_ANS_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('JOB_SEEKER_ANS', models.CharField(max_length=100)),
                ('DISC_PROFILE', models.CharField(max_length=100)),
                ('DISC_ASSESSMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.disc_assessment')),
            ],
        ),
        migrations.CreateModel(
            name='DISC_Assessment_Result',
            fields=[
                ('DISC_ASSESSMENT_RESULT_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('DISC_CATEGORY', models.CharField(max_length=100)),
                ('SCORE', models.IntegerField()),
                ('DISC_ASSESSMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.disc_assessment')),
            ],
        ),
        migrations.CreateModel(
            name='DISC_Characteristics_Dataset',
            fields=[
                ('DISC_CHARACTERISTIC_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DISC_CATEGORY', models.CharField(max_length=300)),
                ('PERSONALITY_TRAIT', models.CharField(max_length=300)),
                ('COGNITIVE_ABILITY', models.CharField(max_length=300)),
                ('EMOTIONAL_REGULATION', models.CharField(max_length=300)),
                ('TENDENCIES', models.CharField(max_length=300)),
                ('WEAKNESSES', models.CharField(max_length=300)),
                ('BEHAVIOUR', models.CharField(max_length=300)),
                ('MOTIVATED_BY', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Seeker_Assessment',
            fields=[
                ('JOB_SEEKER_ASSESSMENT_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=100)),
                ('ASSESSMENT_TYPE', models.CharField(max_length=100)),
                ('ASSESSMENT_ONGOING_STATUS', models.CharField(max_length=100)),
                ('COMPLETION_TIME', models.DateTimeField()),
                ('ASSESSMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.assessment')),
                ('JOB_POST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.job_posting')),
                ('JOB_SEEKER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.job_seeker')),
            ],
        ),
        migrations.CreateModel(
            name='Personality_Assessment',
            fields=[
                ('PERSONALITY_ASSESSMENT_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('PERSONALITY_TEST_TYPE', models.CharField(max_length=100)),
                ('JOB_SEEKER_ASSESSMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.job_seeker_assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Personality_Assessment_Report',
            fields=[
                ('PERSONALITY_ASSESSMENT_REPORT_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Answers_Dataset',
            fields=[
                ('TECH_ANS_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('JOB_SEEKER_ANS', models.CharField(max_length=100)),
                ('IS_CORRECT', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Assessment',
            fields=[
                ('TECHNICAL_ASSESSMENT_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('TECHNICAL_ASSESSMENT_LEVEL', models.CharField(max_length=100)),
                ('JOB_SEEKER_ASSESSMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.job_seeker_assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Assessment_Result',
            fields=[
                ('TECHNICAL_ASSESSMENT_RESULT_ID', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('SCORE', models.IntegerField()),
                ('TECHNICAL_ASSESSMENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.technical_assessment')),
            ],
        ),
        migrations.DeleteModel(
            name='NVI_Questions_Dataset',
        ),
        migrations.RemoveField(
            model_name='disc_questions_dataset',
            name='id',
        ),
        migrations.RemoveField(
            model_name='disc_score_calculation_dataset',
            name='id',
        ),
        migrations.RemoveField(
            model_name='technical_questions_dataset',
            name='id',
        ),
        migrations.AlterField(
            model_name='disc_questions_dataset',
            name='DISC_PROFILE_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disc_score_calculation_dataset',
            name='DISC_PROFILE_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job_position_criteria',
            name='JPC_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job_seeker_work_experience',
            name='END_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technical_questions_dataset',
            name='TECH_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bigfive_assessment_answers',
            name='DIMENSION_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.bigfive_questions_dataset'),
        ),
        migrations.AddField(
            model_name='cognitive_nvi_answers_dataset',
            name='NVI_IMAGE_QUESTION_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.cognitive_nvi_questions_dataset'),
        ),
        migrations.AddField(
            model_name='cognitive_vi_answers_dataset',
            name='VI_QUESTION_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.cognitive_vi_question_dataset'),
        ),
        migrations.AddField(
            model_name='disc_assessment_answer',
            name='DISC_PROFILE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.disc_questions_dataset'),
        ),
        migrations.AddField(
            model_name='disc_assessment_answer',
            name='DISC_PROFILE_SCORE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.disc_score_calculation_dataset'),
        ),
        migrations.AddField(
            model_name='cognitive_assessment',
            name='JOB_SEEKER_ASSESSMENT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.job_seeker_assessment'),
        ),
        migrations.AddField(
            model_name='disc_assessment',
            name='PERSONALITY_ASSESSMENT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.personality_assessment'),
        ),
        migrations.AddField(
            model_name='bigfive_assessment',
            name='PERSONALITY_ASSESSMENT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.personality_assessment'),
        ),
        migrations.AddField(
            model_name='personality_assessment_report',
            name='BIG_FIVE_ASSESSMENT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.bigfive_assessment'),
        ),
        migrations.AddField(
            model_name='personality_assessment_report',
            name='DISC_ASSESSMENT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.disc_assessment'),
        ),
        migrations.AddField(
            model_name='personality_assessment_report',
            name='JOB_SEEKER_ASSESSMENT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.job_seeker_assessment'),
        ),
        migrations.AddField(
            model_name='personality_assessment_report',
            name='PERSONALITY_ASSESSMENT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.personality_assessment'),
        ),
        migrations.AddField(
            model_name='technical_answers_dataset',
            name='TECH_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.technical_questions_dataset'),
        ),
        migrations.AddField(
            model_name='technical_answers_dataset',
            name='TECHNICAL_ASSESSMENT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirexcel_webapp.technical_assessment'),
        ),
    ]
