# Generated by Django 5.0.6 on 2024-10-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirexcel_webapp', '0007_rename_disc_profile_id_disc_score_calculation_dataset_disc_profile_score_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personality_assessment_report',
            old_name='BIG_FIVE_ASSESSMENT_ID',
            new_name='BIGFIVE_ASSESSMENT_ID',
        ),
    ]
